[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[plugins]]
  package = "netlify-plugin-inline-critical-css"
[[plugins]]
	package = "@netlify/plugin-lighthouse"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
